- hosts: localhost
  tasks:
    - name: Create public network
      os_network:
        state: present
        name: public-net
        external: True
        shared: True
        provider_network_type: flat
        provider_physical_network: datacentre
    - name: Create public subnet
      os_subnet:
        state: present
        network_name: public-net
        name: public-subnet
        ip_version: 4
        cidr: 192.168.122.0/24
        gateway_ip: 192.168.122.1
        enable_dhcp: yes
        allocation_pool_start: 192.168.122.130
        allocation_pool_end: 192.168.122.250
        dns_nameservers:
          - 192.168.122.1

    - name: Create private network
      os_network:
        state: present
        name: "{{ netname }}-net"
        external: False
        shared: False

    # - name: Create subnet
    #   os_subnet:
    #     state: present
    #     network_name: "{{ netname }}-net"
    #     name: "{{ netname }}-subnet"
    #     ip_version: 4
    #     cidr: 10.13.0.0/24
    #     gateway_ip: 10.13.0.1
    #     enable_dhcp: yes
    #     dns_nameservers:
    #       - 192.168.122.1
    #
    # - name: Create  router
    #   ignore_errors: yes
    #   os_router:
    #     state: present
    #     name: overcloud-router
    #     network: public-net
    #     external_fixed_ips:
    #       - subnet: public-subnet
    #     interfaces:
    #       - "{{ netname }}-subnet"

    - name: Create {{ sg }} security group
      os_security_group:
        state: present
        name: "{{ sg }}"
    # - name: Allow any ICMP
    #   os_security_group_rule:
    #     security_group: "{{ sg }}"
    #     protocol: icmp
    #     remote_ip_prefix: 0.0.0.0/0

    - name: Allow any TCP connection
      os_security_group_rule:
        security_group: "{{ sg }}"
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0

    - name: Allow any UDP connection
      os_security_group_rule:
        security_group: "{{ sg }}"
        protocol: udp
        remote_ip_prefix: 0.0.0.0/0

    - name: Update quotas
      os_quota:
        name: admin
        backup_gigabytes: -1
        backups: -1
        cores: -1
        fixed_ips: -1
        floating_ips: -1
        gigabytes: -1
        injected_file_size: -1
        injected_files: -1
        injected_path_size: -1
        instances: -1
        port: -1
        key_pairs: -1
        per_volume_gigabytes: -1
        properties: -1
        ram: -1
        security_group_rule: -1
        security_group: -1
        server_group_members: -1
        server_groups: -1
        snapshots: -1
        volumes: -1

    - name: Create keypair {{keyname}}
      os_keypair:
          state: present
          name: "{{keyname}}"
          public_key_file: "{{ '~' | expanduser }}/.ssh/authorized_keys"
    - name: "Create flavors"
      os_nova_flavor: state={{ item.state }} name={{ item.name }} ram={{ item.ram }} vcpus={{ item.vcpus }} disk={{ item.disk }} ephemeral={{ item.ephemeral }} flavorid={{ item.flavorid }}
      with_items:
        - { state: 'present', name: 'm1.small' , ram: '512' , vcpus: '1' , disk: '0' , ephemeral: '1' , flavorid: '1' }
        - { state: 'present', name: 'm1.fat' , ram: '51200' , vcpus: '16' , disk: '0' , ephemeral: '15' , flavorid: '2' }
        - { state: 'present', name: 'm1.medium' , ram: '1024' , vcpus: '1' , disk: '0' , ephemeral: '0' , flavorid: '3' }
        - { state: 'present', name: 'm1.large' , ram: '2048' , vcpus: '8' , disk: '0' , ephemeral: '0' , flavorid: '4' }
        - { state: 'present', name: 'm1.xlarge' , ram: '8192' , vcpus: '8' , disk: '0' , ephemeral: '0' , flavorid: '5' }
        - { state: 'present', name: 'm2.large' , ram: '8192' , vcpus: '2' , disk: '0' , ephemeral: '0' , flavorid: '6' }
        - { state: 'present', name: 'm3.xlarge' , ram: '16384' , vcpus: '4' , disk: '0' , ephemeral: '0' , flavorid: '7' }
        - { state: 'present', name: 's1.large' , ram: '2048' , vcpus: '2' , disk: '0' , ephemeral: '0' , flavorid: '8' }
        - { state: 'present', name: 'ocp.medium' , ram: '16384' , vcpus: '4' , disk: '50' , ephemeral: '0' , flavorid: '9' }
