- hosts: localhost
  tasks:
    - name: Create public network
      os_network:
        state: present
        name: public-net
        external: True
        shared: True
        provider_network_type: flat
        provider_physical_network: datacentre
      register: public-net
    - name: Create public subnet
      os_subnet:
        state: present
        network_name: public-net
        name: public-subnet
        ip_version: 4
        cidr: 10.0.0.0/24
        gateway_ip: 10.0.0.1
        enable_dhcp: yes
        allocation_pool_start: 10.0.0.50
        allocation_pool_end: 10.0.0.250
        dns_nameservers:
          - 10.0.0.1
      register: public-subnet


    - name: Create private network
      os_network:
        state: present
        name: private-net
        external: False
        shared: False
      register: private-net

    - name: Create subnet
      os_subnet:
        state: present
        network_name: private-net
        name: private-subnet
        ip_version: 4
        cidr: 10.13.0.0/24
        gateway_ip: 10.13.0.1
        enable_dhcp: yes
        dns_nameservers:
          - 8.8.8.8
      register: private-subnet
      
    - name: Create the test router
      ignore_errors: yes
      os_router:
        state: present
        name: overcloud-nova-router
        network: public-net
        external_fixed_ips:
          - subnet: public-subnet
        interfaces:
          - private-subnet
