---
    - name: Download  {{ item.imagename }} images
      get_url: url={{ item.url }} dest={{ item.dest }}
    # - name: modify dowloaded images
    #   script: files/modify-images.sh
    #   when: item.imagename == 'fedora26-server'
    - name: Upload {{ item.imagename }} to openstack
      os_image:
          name: '{{ item.imagename }}'
          container_format: bare
          disk_format: qcow2
          state: present
          is_public: yes
          filename: './files/{{ item.imagename }}'
